b=rgb2gray(imread('clp.png'));
subplot(5,2,1);
imshow(b);
title('og')
subplot(5,2,2);
imhist(b);
title('og');
a=rgb2gray(imread('clp2.png'));
subplot(5,2,3);
imshow(a);
title('bright')
subplot(5,2,4);
imhist(a);
title('bright');
c=rgb2gray(imread('clp3.png'));
subplot(5,2,5);
imshow(c);
title('dark')
subplot(5,2,6);
imhist(c);
title('dark');
d=rgb2gray(imread('clp_cont_max.png'));
subplot(5,2,7);
imshow(d);
title('cont_max')
subplot(5,2,8);
imhist(d);
title('cont_max');
E=rgb2gray(imread('clp_cont_min.png'));
subplot(5,2,9);
imshow(E);
title('cont_min')
subplot(5,2,10);
imhist(E);
title('cont_min');