a=imread('clpsm.jpg');
b=imdivide(a,2);
c=immultiply(a,2);
d=imadd(b,128);
subplot(2,3,1);%add,su,div
imshow(a);
title('original');
subplot(2,3,2);%add,su,div
imshow(a-128);
title('sub(128)');
subplot(2,3,3);%add,su,div
imshow(a+128);
title('add(128)');
subplot(2,3,4);%add,su,div
imshow(b);
title('a/2');
subplot(2,3,5);%add,su,div
imshow(c);
title('a*2');
subplot(2,3,6);%add,su,div
imshow(d);
title('a/2+128');