a=imread('clpsm4.png');
ax=rgb2gray(a);
sp=imnoise(ax,'salt & pepper',0.02);
avf1=fspecial('average',[5 5]);
av1=imfilter(a,avf1);
avf2=fspecial('average',[7 7]);
av2=imfilter(a,avf2);
avf3=fspecial('average',[9 9]);
av3=imfilter(a,avf3);
medf=medfilt2(sp);
lpf=fspecial('laplacian',0.3);
lp=imfilter(a,lpf);
fun = @(x) median(x(:));
nl = nlfilter(ax,[3 3],fun);
subplot(1,3,1);
imshow(a);
title('original');
subplot(1,3,2);
imshow(lp);
title('laplacian');
xlabel('filter');
subplot(1,3,3);
imshow(nl);
title('non-linear');
xlabel('median');
figure(2);
subplot(1,2,1);
imshow(sp);
title('salt and pepper');
xlabel('noise');
subplot(1,2,2);
imshow(medf);
title('median');
xlabel('s&p n');
figure(3);
subplot(1,3,1);
imshow(av1);
title('average');
xlabel('5x5');
subplot(1,3,2);
imshow(av2);
title('average');
xlabel('7x7');
subplot(1,3,3);
imshow(av3);
title('average');
xlabel('9x9');