ax=imread('clpsm7.jpg');
a=rgb2gray(ax);
an=imnoise(a,'gaussian');
a1=wiener2(a,[7 7]);
a2=wiener2(a,[13 13]);
av1=fspecial('average',[7 7]);
av2=fspecial('average',[13 13]);
a3=imfilter(a,av1);
a4=imfilter(a,av2);
subplot(2,3,1);
imshow(a);
title('original');
subplot(2,3,2);
imshow(a1);
title('weiner');
xlabel('[7 7]');
subplot(2,3,3);
imshow(a2);
title('weiner');
xlabel('[13 13]');
subplot(2,3,4);
imshow(an);
title('noise');
xlabel('gaussian');
subplot(2,3,5);
imshow(a3);
title('average');
xlabel('[7 7]');
subplot(2,3,6);
imshow(a4);
title('average');
xlabel('[13 13]');

