ixx=imread('clpsm2.png');
ix=rgb2gray(ixx);
i=double(ix);
figure
f=fspecial('laplacian',0.9);
i1=imfilter(i,f);
i2=imcomplement(i);
i3=imfilter(i2,f);
i4=i3-i2;
subplot(2,2,1);
imshow(ix)
title('original');
subplot(2,2,2);
imshow(i3)
title('laplacian');
xlabel('x=lapl(i*)');
subplot(2,2,4);
imshow(i4)
title('edge');
xlabel('x=lapl(i*)-lapl(i)');
subplot(2,2,3);
imshow(imcomplement(ix));
title('complement');