aaa=imread('clpsm9.jpg');
aa=rgb2gray(aaa);
a=imbinarize(aa);
A = fft2(a);
A_abs = abs(A);
A_shifted = fftshift(A_abs);
A_trans = log(1+abs(A_shifted));
A_ifft = ifftshift(A_trans);
subplot(2,4,1);
imshow(a);
title('image');
subplot(2,3,2);
plot(A,'.');
title('FFT');
subplot(2,3,3);
freqz2(A_abs);
title('frequency spectrum');
subplot(2,3,4);
freqz2(A_shifted);
title('Centred ft');
subplot(2,3,5);
freqz2(A_trans);
title('Enhanced ft');
subplot(2,3,6);
freqz2(A_ifft);
title('IFFT');
