aaa=imread('clp.png');
aa=rgb2gray(aaa);
a1=imresize(aa,[515 515]);
a=im2double(a1);
A=fft2(a);
h=fspecial('sobel');
h_padded=padarray(h,[256 256],'symmetric','both');
H=fft2(h_padded);
G=A.*H;
g1=ifft(G);
g=im2uint8(g1);
subplot(2,2,1);
imshow(I);
title('Original Image');
subplot(2,2,2);
freqz2(A);
title('FFT original');
subplot(2,2,3);
plot(abs(G));
title('output ft');
subplot(2,2,4);
imshow(g,[]);
title('output');